version: '2.2'
services:
# DMZ network
  wordpress:
    build: ./wordpress
    container_name: wordpress
    hostname: 'wordpress'

    networks:
      DMZ-net:
        ipv4_address: 172.16.10.10

networks:
  DMZ-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.10.0/24
        gateway: 172.16.10.1
